language: scala
sudo: required
dist: xenial

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/spark
    - $HOME/.sbt/

jdk:
  - openjdk8

scala:
- 2.11.2

sudo: false

addons:
  apt:
    packages:
        - axel

install:
  # Download spark 2.4.0
  - "[ -f spark ] || mkdir spark && cd spark && axel https://archive.apache.org/dist/spark/spark-2.4.0/spark-2.4.0-bin-hadoop2.7.tgz && cd .."
  - "tar -xf ./spark/spark-2.4.0-bin-hadoop2.7.tgz"
  - "export SPARK_HOME=`pwd`/spark-2.4.0-bin-hadoop2.7"
  - echo "spark.yarn.jars=$SPARK_HOME/jars/*.jar" > $SPARK_HOME/conf/spark-defaults.conf
  - "git clone https://github.com/graphsense/graphsense-clustering.git && cd graphsense-clustering && sbt publishLocal && cd .."

script:
   - sbt ++$TRAVIS_SCALA_VERSION test

notifications:
  email:
    recipients:
      - rainer.stuetz@ait.ac.at
    on_success: never
    on_failure: always
